[settings]
idiomatic_version_file_enable_tools = ["python"]
env_shell_expand = true

[tools]
bat = "latest"
gh = "latest"
eza = "latest"
fzf = "latest"
fd = "latest"
delta = "latest"
shellcheck = "latest"
ripgrep = "latest"
lazygit = "latest"
elixir = "1.20.0-rc.1-otp-28"
erlang = "28.3"
uv = "latest"
rebar = "3.26.0"
ruby = "3.4.8"
nodejs = "22.22.0"
python = "3.11.14"
diffoci = "latest"
android-sdk = "11.0"
java = "temurin-17.0.13+11"
usage = "latest"
